### ISSUE TITLE
Tabular data, regression problem, MSE loss and mean_squared_error mismatch

### ISSUE THREAD

**Issue by AlexGrig** [fastai/fastai#1486]
**Describe the bug**

I have described the bug in more details on forums.fast.ai [here](https://forums.fast.ai/t/tabular-data-regression-problem-mse-loss-and-mean-squared-error-mismatch/35229/2)

Basically, the mse loss on the validation set and metric `mean_squared_error` give very different results. 

The solution is also posted there. The problem is that the shapes of predictions and targets are (bs,1) and (bs,). Because of the broadcasting the result of the metric computation is incorrect. Other metrics may also be affected by the same bug.

**Provide your installation details**
python        : 3.7.2
fastai        : 1.0.40.dev0
fastprogress  : 0.1.18
torch         : 1.0.0

**Comment by brownaa** [comment]
This does not appear to have made it into the releases. Was there another fix that resolved this?

**Comment by sgugger** [comment]
This has been fixed a while ago and is in the latest release. Outputs and targets are flattened before computing the metrics: https://github.com/fastai/fastai/blob/c655762c3dc835ea61ad9143d84f1c3b47fe60f4/fastai/metrics.py#L82

**Comment by brownaa** [comment]
> This has been fixed a while ago and is in the latest release. Outputs and targets are flattened before computing the metrics:
> 
> https://github.com/fastai/fastai/blob/c655762c3dc835ea61ad9143d84f1c3b47fe60f4/fastai/metrics.py#L82

It looks like the fix you made for this issue [2c97552](https://github.com/fastai/fastai/commit/2c975521aa8430bfafbbb27255c0c711a1354096) uses **.squeeze_check()**

https://github.com/fastai/fastai/blob/2c975521aa8430bfafbbb27255c0c711a1354096/fastai/metrics.py#L76

Maybe the clarification I need is to be sure which solution is the correct one because we are still seeing that the MSE loss is more that the square of RMSE.

**Comment by sgugger** [comment]
It’s hard to know what you think the bug is if you don’t give us any code. If you use directly rmse_loss as a metric, you won’t get the square root of the mse loss since it averages the rmse losses of each batch. You should use RMSELoss() to have the real value.

**Comment by brownaa** [comment]
Thanks. Your last comment help me sort out my issue. Thanks.
